export const contactPl = {
  meta: {
    title: 'Umów rozmowę · mioduszewsky',
    description: 'Umów 15-minutową rozmowę albo napisz. Opowiedz, co dziś nie działa i co trzeba zbudować. Powiem wprost, czy jestem właściwą osobą.',
  },
  back: 'Wróć',
  logoAria: 'mioduszewsky. Wróć na stronę główną.',
  label: '( Następny krok · jedna konkretna rozmowa )',
  h1: 'Umów 15-minutową rozmowę.',
  h2: 'Albo po prostu napisz.',
  lead: 'Napisz, co masz dziś, nawet jeśli nie ma jeszcze nic. Co nie działa i po co ma powstać nowa strona. Powiem ci wprost, czy jestem właściwą osobą i co zbudowałbym najpierw. Bez ciśnienia. Bez skryptu sprzedażowego.',
  call: {
    title: 'Umów rozmowę',
    desc: 'Wybierz termin. 15 minut, wideo, bez zobowiązań.',
    consent: 'Kalendarz obsługuje Google. Po jego wyświetleniu Google może zapisać plik cookie na twoim urządzeniu, żeby pokazać dostępne terminy.',
    show: 'Pokaż kalendarz',
    noteBefore: 'Kalendarz się nie wyświetla?',
    email: 'Napisz do mnie',
    noteAfter: 'i znajdziemy termin.',
    fallback: 'Napisz, żeby umówić rozmowę',
    fallbackNote: 'Kalendarz jest właśnie podłączany. Na razie napisz maila. Wrócę z terminem.',
    iframeTitle: 'Umów 15-minutową rozmowę',
    mailSubject: 'Umówmy rozmowę',
  },
  form: {
    title: 'Albo napisz wiadomość',
    desc: 'Trzy pola. Tyle.',
    name: 'Imię',
    email: 'E-mail',
    message: 'O czym chcesz porozmawiać?',
    honeypot: 'Zostaw to pole puste',
    consentBefore: 'Zgadzam się na przetwarzanie moich danych w celu odpowiedzi na tę wiadomość, zgodnie z',
    privacy: 'polityką prywatności',
    terms: 'warunkami korzystania ze strony',
    send: 'Wyślij wiadomość',
    successTitle: 'Dzięki. Wiadomość wysłana.',
    successText: 'Czytam każdą wiadomość osobiście. Jeśli wolisz od razu porozmawiać, wybierz termin:',
    missing: 'Uzupełnij wszystkie trzy pola.',
    invalidEmail: 'Sprawdź adres e-mail. Coś się w nim nie zgadza.',
    missingConsent: 'Zaznacz zgodę, żebym mógł odpowiedzieć.',
    sending: 'Wysyłam…',
    error: 'Coś poszło nie tak. Napisz bezpośrednio na kacper@mioduszewsky.com.',
    fallbackSubject: 'Wiadomość ze strony od ',
  },
  other: '( Możesz też )',
  remote: 'Wrocław, Polska · pracuję zdalnie',
  terms: 'Warunki',
  privacy: 'Prywatność',
} as const;
