export const contactPl = {
  meta: {
    title: 'Umów rozmowę · mioduszewsky',
    description: 'Bezpłatna 15-minutowa rozmowa przez wideo albo krótka wiadomość. Pokaż, co masz dziś. Powiem Ci, czy to projekt dla mnie i od czego bym zaczął.',
  },
  back: 'Wróć',
  logoAria: 'mioduszewsky. Wróć na stronę główną.',
  label: '( Następny krok · 15 minut )',
  h1: 'Bezpłatne 15 minut.',
  h2: 'Rozmowa przez wideo. Albo po prostu napisz.',
  lead: 'Pokaż mi, co masz dziś. Może to być stara strona, szkic albo nic. Powiem Ci, czy to projekt dla mnie i od czego bym zaczął. Piętnaście minut przez wideo, bezpłatnie.',
  call: {
    title: 'Wybierz termin',
    desc: 'Bezpłatnie. 15 minut rozmowy przez wideo.',
    consent: 'Kalendarz obsługuje Google. Po jego wyświetleniu Google może zapisać plik cookie na twoim urządzeniu, żeby pokazać dostępne terminy.',
    show: 'Pokaż kalendarz',
    noteBefore: 'Kalendarz się nie wyświetla?',
    email: 'Napisz do mnie',
    noteAfter: 'i znajdziemy termin.',
    fallback: 'Napisz, żeby umówić rozmowę',
    fallbackNote: 'Kalendarz jest właśnie podłączany. Na razie napisz maila. Wrócę z terminem.',
    iframeTitle: 'Umów bezpłatne 15 minut rozmowy',
    mailSubject: 'Umówmy rozmowę',
  },
  form: {
    title: 'Albo napisz wiadomość',
    desc: 'Trzy pola. Tyle.',
    name: 'Imię',
    email: 'E-mail',
    message: 'O czym chcesz porozmawiać?',
    honeypot: 'Zostaw to pole puste',
    consentBefore: 'Zgadzam się na przetwarzanie moich danych w celu odpowiedzi na tę wiadomość, zgodnie z',
    privacy: 'polityką prywatności',
    terms: 'warunkami korzystania ze strony',
    send: 'Wyślij wiadomość',
    successTitle: 'Dzięki. Wiadomość wysłana.',
    successText: 'Czytam każdą wiadomość osobiście. Jeśli wolisz od razu porozmawiać, wybierz termin:',
    missing: 'Uzupełnij wszystkie trzy pola.',
    invalidEmail: 'Sprawdź adres e-mail. Coś się w nim nie zgadza.',
    missingConsent: 'Zaznacz zgodę, żebym mógł odpowiedzieć.',
    sending: 'Wysyłam…',
    error: 'Coś poszło nie tak. Napisz bezpośrednio na kacper@mioduszewsky.com.',
    fallbackSubject: 'Wiadomość ze strony od ',
  },
  other: '( Możesz też )',
  remote: 'Wrocław, Polska · pracuję zdalnie',
  terms: 'Warunki',
  privacy: 'Prywatność',
} as const;
