export const homePl = {
  meta: {
    title: 'mioduszewsky · strony internetowe, AI i aplikacje',
    description: 'Strony internetowe od pierwszej rozmowy do publikacji. Układam treść, projektuję i buduję. Tworzę też wdrożenia AI, aplikacje i systemy.',
  },
  nav: { cta: 'Umów 15 minut', sticky: 'Umów 15 minut', stickyAria: 'Umów 15-minutową rozmowę' },
  hero: {
    label: '( Strony · AI · aplikacje )',
    aria: 'Dobra strona mówi za Ciebie.',
    line1: 'Dobra strona',
    em: 'mówi',
    line3: 'za Ciebie',
    sub: 'Buduję strony internetowe, wdrożenia AI i aplikacje. *Całość robię sam*, więc nie zszywasz projektu z kawałków od kilku wykonawców.',
  },
  problem: {
    label: '( Problem )',
    h1: 'Potrzebujesz strony.',
    h2: 'Nagle masz cały projekt na głowie.',
    intro: 'Zaczyna się od „potrzebuję strony”. Potem dochodzi treść, projekt, domena i wdrożenie. Ile z tego spada na Ciebie, zależy od tego, w którym miejscu jesteś dzisiaj. Zwykle w jednym z trzech:',
    rows: [
      ['Strony jeszcze nie ma', 'Wiesz, że jej potrzebujesz, ale nie wiesz, od czego zacząć ani co przygotować.'],
      ['Biznes poszedł dalej. Strona została.', 'Oferta się zmieniła, firma wygląda dziś inaczej, a strona nadal pokazuje jej starą wersję.'],
      ['Strona powstała, ale niewiele z niej wynika', 'Klient nadal musi się domyślać, co oferujesz i co ma zrobić dalej.'],
    ],
    close: 'Strona składa się z kilku różnych decyzji: co powiedzieć, jak to ułożyć, jak pokazać i jak zbudować. *Ja prowadzę te rzeczy razem*, żeby na końcu powstała jedna działająca całość.',
  },
  work: {
    label: 'Wybrane realizacje',
    hint: '( to nie są zrzuty ekranu, tylko działające strony )',
    eskapizm: 'Firma zajmująca się planowaniem podróży po Azji. Strona, proces sprzedaży, płatności, aplikacja klienta, CMS i narzędzia do obsługi. Całość zbudowana od zera jako jeden system.',
    eskapizmAlt: 'eskapizm.com. Przewiń działającą stronę.',
    liveNote: 'psst, działa.\nprzewiń',
    aigor: 'Strona kolekcji sztuki. Prace, artyści, historia pozyskania dzieł, newsletter i dwie wersje językowe. Całość ułożona tak, żeby prowadzić przez historię kolekcji.',
    aigorAlt: 'igorgrabowski.com. Przewiń działającą stronę.',
    aigorNote: 'to one pager.\ntu klikasz',
    more: 'Więcej realizacji',
    glassstone: 'Strona firmy z galerią realizacji, narzędziami do publikacji i panelem administracyjnym. Coś, z czego firma korzysta także po publikacji.',
    cannversity: 'Landing page dla doradztwa w branży konopnej. Złożona oferta ułożona w prostą strukturę, którą da się szybko zrozumieć.',
    decksName: 'Prezentacje projektowe',
    decks: 'Interaktywne prezentacje i modele finansowe, które zderzają pomysł z realnymi ograniczeniami i decyzją biznesową.',
    disclaimer: 'Te realizacje pokazują zakres i rodzaj wykonanej pracy. Nie są obietnicą przychodu, konwersji ani oszczędności.',
  },
  manifest: {
    line1: 'Nie chodzi o kolejny etap.',
    line2: 'Chodzi o ten ostatni.',
    line3: 'Wchodzisz live.',
    note: 'teraz.',
    sub: 'Wysyłasz stronę klientom. Puszczasz na nią kampanię. Pokazujesz partnerom. Przestajesz ją robić i zaczynasz jej używać.',
  },
  how: {
    label: '( Jak pracuję )',
    h1: 'Płacisz za stronę.',
    h2: 'Masz ją z głowy.',
    oldTitle: 'Typowy proces',
    oldList: ['Piszesz brief.', 'Ktoś robi treść.', 'Ktoś projektuje.', 'Ktoś inny wdraża.', 'Ty spinasz resztę.'],
    oldOut: '',
    newTitle: 'U mnie',
    newList: ['Rozmawiamy o biznesie.', 'Ustalam, co ma powstać.', 'Układam treść i strukturę.', 'Projektuję i buduję.', 'Publikujemy.'],
    newOut: 'Od pierwszej rozmowy do publikacji rozmawiasz z *tą samą osobą*.',
    why1: 'Siemka, tu Kacper. Zanim zacząłem robić strony, pracowałem przy prowadzeniu projektów i startupów. Designu i developmentu nauczyłem się później, bo chciałem sam zamieniać pomysły w działające produkty.',
    why2: 'Biorę to, co masz w głowie i w biznesie, i przekładam na działającą stronę. Patrzę na cały ciąg: decyzja, oferta, treść, design, wdrożenie i publikacja.',
    why3: 'eskapizm to spółka, którą współprowadzę. Cannversity powstało, kiedy wchodziłem głębiej w branżę konopną. Oba nauczyły mnie patrzeć na stronę przez pryzmat tego, co ma zrobić dla firmy.',
  },
  offer: {
    label: '( Oferta )',
    badge: '30 dni poprawek po publikacji',
    h1: 'Kompletna strona',
    h2: 'internetowa',
    price: 'od 3 500 zł',
    say: 'Nie przychodzisz do mnie po sam design albo samo wdrożenie. Ustalamy, czego potrzebuje Twój biznes, a potem biorę na siebie treść, projekt, technologię i publikację.',
    say2: 'Nie musisz wiedzieć, ile ma być podstron ani na czym to ma być zbudowane. Od tego jest pierwsza rozmowa: mówisz, co robi Twoja firma, a ja mówię, co trzeba zbudować i ile to kosztuje.',
    assure: 'Zakres i cena są znane przed startem. Jeśli po rozmowie uznam, że strona nie jest teraz właściwym ruchem, też Ci to powiem.',
    includesLabel: 'Co dostajesz',
    includes: [
      'Treść i strukturę strony',
      'Projekt przygotowany pod Twój biznes',
      'Wersję mobilną',
      'Formularze i potrzebne integracje',
      'Podpięcie domeny i SSL',
      'Podstawowy pomiar od dnia publikacji',
      '30 dni poprawek po starcie',
    ],
    forWhom: 'Dla osób, które wiedzą, że potrzebują strony, i wolą oddać ten temat komuś, kto zrobi całość.',
    other: 'Pozostałe usługi',
    otherIntro: 'To osobne zakresy, wyceniane oddzielnie.',
    beyond: [
      { nr: '01', n: 'Wdrożenie AI', p: 'od 4 500 zł', d: 'Masz konkretny proces, który zabiera za dużo ręcznej pracy. Rozpisuję go i buduję rozwiązanie: automatyzację, agenta, integrację albo panel.' },
      { nr: '02', n: 'Aplikacja lub system', p: 'od 11 000 zł', d: 'Pierwsza działająca wersja produktu, aplikacji, dashboardu albo systemu dla firmy.' },
      { nr: '03', n: 'Stały rozwój produktu', p: 'od 5 500 zł miesięcznie', d: 'Dla projektów, które po pierwszej wersji mają być dalej rozwijane. Ustalamy stałą współpracę i pracujemy nad kolejnymi funkcjami, wersjami i decyzjami produktowymi.' },
    ],
    fine: 'Dokładny zakres i cena są znane przed startem · maksymalnie trzy aktywne projekty jednocześnie.',
    exclusionLabel: 'Poza zakresem',
    exclusion: 'Długoterminowe prowadzenie reklam, stałe SEO i gwarantowane wyniki sprzedażowe.',
  },
  process: {
    label: '( Proces )',
    h1: 'Od pierwszych 15 minut',
    h2: 'do publikacji.',
    steps: [
      ['Najpierw rozmawiamy', 'Pokazujesz mi, co masz dziś, czego potrzebujesz i po co ma powstać nowa strona. Zaczynamy od 15 minut.'],
      ['Dostajesz konkretny zakres', 'Wiesz, co robię, czego nie robię, ile to kosztuje i jak rozliczamy projekt.'],
      ['Rezerwujesz termin', 'Po akceptacji zakresu opłacasz projekt i rezerwuję termin. Mniejsze realizacje są płatne w całości z góry, większe dzielimy na etapy opłacane przed startem każdego z nich.'],
      ['Biorę się za robotę', 'Układam treść, projektuję i buduję zgodnie z tym, co ustaliliśmy na początku.'],
      ['Wchodzimy live', 'Publikuję stronę, podpinam potrzebne rzeczy i możesz zacząć normalnie z niej korzystać.'],
      ['Potem zależy od projektu', 'Po publikacji masz 30 dni poprawek. Jeśli budujemy coś większego, możemy umówić się na stały rozwój produktu.'],
    ],
  },
  faq: {
    label: '( Pytania przed startem )',
    items: [
      ['Czy AI może zbudować stronę za mnie?', 'Może wygenerować tekst, layout i kod. Sam też korzystam z AI. Trudniejsza część to decyzje: co zostawić, co wyrzucić i czy całość faktycznie pasuje do biznesu.'],
      ['Czy muszę mieć gotowe teksty?', 'Nie. Mogę je stworzyć w ramach projektu, ale potrzebuję od Ciebie prawdziwych informacji o ofercie, klientach i biznesie. Nie wymyślam wyników ani opinii.'],
      ['Czy robisz tylko strony internetowe?', 'Strony są głównym kierunkiem. Buduję też wdrożenia AI, aplikacje, panele i wewnętrzne systemy, jeśli właśnie tego wymaga projekt.'],
      ['Czy jesteś agencją?', 'Nie, działam sam. Rozmawiasz ze mną i ja prowadzę projekt od pierwszej rozmowy do publikacji. Maksymalnie trzy aktywne projekty naraz.'],
      ['Co obejmuje 30 dni poprawek?', 'Przez 30 dni po publikacji bez dodatkowej opłaty naprawiam rzeczy z uzgodnionego zakresu, które nie działają tak, jak ustaliliśmy. Nowe elementy i zmiany wyceniam osobno.'],
      ['Czy gwarantujesz wyniki?', 'Nie gwarantuję przychodu ani konkretnego wyniku marketingowego. Odpowiadam za to, co buduję i co ustaliliśmy w zakresie. Wynik zależy też od oferty, ruchu, rynku i tego, co dzieje się po publikacji.'],
    ],
  },
  footer: {
    label: '( Pogadajmy )',
    h1: 'Masz stronę do zrobienia.',
    h2: 'Sprawdźmy, co ma powstać.',
    sub: 'Pokaż mi, co masz dziś. Może to być stara strona, szkic albo nic. Powiem Ci, czy to projekt dla mnie i od czego bym zaczął.',
    write: 'albo po prostu napisz',
    contact: 'Kontakt',
    badge: 'Wrocław, Polska · pracuję zdalnie ·',
    availability: 'Dostępność',
    availability1: 'Maksymalnie trzy aktywne projekty jednocześnie',
    availability2: 'Zaczynamy od 15 minut',
    top: 'Wróć na początek',
    built: 'Zaprojektowane i zbudowane przez jedną osobę',
    terms: 'Warunki',
    privacy: 'Prywatność',
  },
} as const;
