export const homePl = {
  meta: {
    title: 'mioduszewsky · strony internetowe, AI i aplikacje',
    description: 'Planuję, piszę, projektuję i buduję strony internetowe od pierwszej rozmowy do publikacji. Tworzę też wdrożenia AI, aplikacje i systemy.',
  },
  nav: { cta: 'Umów rozmowę', sticky: 'Umów 15 minut', stickyAria: 'Umów 15-minutową rozmowę' },
  hero: {
    label: '( Strony · AI · aplikacje )',
    aria: 'Strona, za którą nie musisz się tłumaczyć.',
    line1: 'Strona, za którą',
    struck: 'musisz',
    note: 'nie musisz',
    line3: 'się tłumaczyć.',
    sub: 'Planuję, piszę, projektuję i buduję stronę od początku do publikacji. Prowadzę cały projekt sam i biorę odpowiedzialność za całość.',
  },
  problem: {
    label: '( Problem )',
    h1: 'Mieć stronę to jedno.',
    h2: 'Móc spokojnie wysłać ją klientowi to drugie.',
    intro: 'Może dopiero zaczynasz. Może projekt utknął w połowie. A może strona działa, ale nie robi tego, po co powstała. Najczęściej wygląda to tak:',
    rows: [
      ['Nie wiesz, od czego zacząć', 'Najpierw treść, projekt czy wykonanie? Decyzji jest za dużo, więc pomysł nadal jest tylko pomysłem.'],
      ['Firma poszła dalej. Strona została z tyłu', 'Twój biznes się zmienił. Strona nadal pokazuje jego starą wersję.'],
      ['Strona z AI powstała szybko', 'Tylko oferta nadal nie jest jasna.'],
    ],
    close: 'Problemem rzadko jest brak kolejnego narzędzia. Trzeba wiedzieć, co zbudować i czy można już spokojnie pokazać to klientom. Tym zajmuję się ja.',
  },
  work: {
    label: 'Wybrane realizacje',
    hint: '( ekrany można przewijać, to działające projekty )',
    eskapizm: 'Platforma do planowania podróży: strona publiczna, proces sprzedaży, płatności, aplikacja klienta, CMS i narzędzia operacyjne. Zaprojektowane i zbudowane od zera jako jeden połączony system.',
    eskapizmAlt: 'eskapizm.com. Przewiń działającą stronę.',
    liveNote: 'psst, działa.\nprzewiń',
    aigor: 'Strona kolekcji sztuki: prace, artyści i historia pozyskania dzieł. Projekt prowadzi odbiorcę przez historię kolekcji.',
    aigorAlt: 'igorgrabowski.com. Przewiń działającą stronę.',
    more: 'Więcej realizacji',
    glassstone: 'Strona firmowa z galerią realizacji, narzędziami do publikacji i panelem administracyjnym. System, z którego firma nadal korzysta po publikacji.',
    cannversity: 'Platforma, która porządkuje złożoną ofertę i szerszą strategię w strukturę zrozumiałą dla odbiorcy.',
    decksName: 'Wewnętrzne prezentacje projektowe',
    decks: 'Interaktywne prezentacje i modele finansowe, które łączą pomysł z realnymi ograniczeniami i decyzją biznesową.',
    disclaimer: 'Te realizacje pokazują zakres i rodzaj wykonanej pracy. Nie są obietnicą przychodu, konwersji ani oszczędności.',
  },
  manifest: {
    line1: 'Nie chodzi o kolejny etap.',
    line2: 'Chodzi o publikację.',
    line3: 'Strona trafia do ludzi.',
    note: 'naprawdę.',
    sub: 'Możesz wysłać ją w mailu. Skierować na nią kampanię. Pokazać klientowi. I rozwijać po publikacji.',
  },
  how: {
    label: '( Jak pracuję )',
    h1: 'Dobra strona nie ma być najbardziej dopieszczona.',
    h2: 'Ma robić swoją robotę.',
    oldTitle: 'Typowy proces',
    oldList: ['Piszesz brief.', 'Jedna osoba projektuje stronę.', 'Druga pisze treść.', 'Programista dostaje gotowe pliki na końcu.', 'Każdy widzi tylko swój kawałek projektu.'],
    oldOut: 'A ty pilnujesz, żeby te kawałki nadal do siebie pasowały.',
    newTitle: 'Mój sposób pracy',
    newList: ['Co sprzedajesz?', 'Kto ma to zrozumieć?', 'Co ma zrobić po wejściu na stronę?', 'Co jest potrzebne, a co można wyrzucić?', 'Dopiero wtedy piszę, projektuję i buduję.'],
    newOut: 'Przez cały projekt rozmawiasz bezpośrednio ze mną.',
    why1: 'Za mioduszewsky stoję ja, nie agencja. Mam na imię Kacper i buduję z Wrocławia. Robię rzeczy, które mają działać także wtedy, gdy opadnie pierwsze wrażenie.',
    why2: 'Nie sprzedaję się jako najlepszy specjalista od wszystkiego. Dobry projektant może stworzyć ładniejszy system. Wyspecjalizowany programista może napisać bardziej zaawansowany kod. Tyle że cały projekt nie kończy się na jednej z tych rzeczy.',
    why3: 'Pracuję tam, gdzie projekty najczęściej się rozjeżdżają: decyzja, oferta, treść, projekt, budowa i publikacja. Jedna całość, jedna odpowiedzialność.',
    why4: 'eskapizm i Cannversity, które widzisz wyżej, nie są realizacjami dla klientów. To moje własne projekty. Zanim uruchomię ten sposób pracy u klienta, sprawdzam go we własnym biznesie.',
  },
  offer: {
    label: '( Oferta )',
    badge: '30 dni poprawek po publikacji',
    h1: 'Strona internetowa',
    h2: 'od rozmowy do publikacji',
    price: 'od 3 500 zł',
    say: 'Strona, która jasno pokazuje ofertę i jest gotowa do pokazania klientom, partnerom albo inwestorom. Na pierwszej rozmowie ustalam, czy wystarczy jedna konkretna strona, czy potrzebna jest pełniejsza witryna. Nie musisz rozstrzygać tego sam.',
    assure: 'Zakres i cena są ustalone przed startem. Jeśli strona nie jest tu właściwym ruchem, powiem ci to wprost. Z rozmowy i tak wyjdziesz z jednym konkretnym następnym krokiem.',
    includesLabel: 'Co dostajesz',
    includes: [
      'Ofertę opisaną słowami zrozumiałymi dla twoich klientów',
      'Projekt, który wygląda jak twoja firma, nie jak gotowy szablon',
      'Jedną osobę od pierwszej rozmowy do publikacji',
      'Wersję mobilną, formularze, domenę i SSL po mojej stronie',
      'Działającą stronę z podstawowym pomiarem od pierwszego dnia',
      '30 dni poprawek po publikacji, bez dodatkowej opłaty',
    ],
    forWhom: 'Dla właścicieli firm, osób rozwijających własny projekt i zespołów, które potrzebują wiarygodnej strony gotowej do pokazania klientom.',
    other: 'Pozostałe usługi',
    otherIntro: 'To osobne usługi, wyceniane oddzielnie. Wiele osób zaczyna od strony, ale jeśli potrzebujesz właśnie tego, możemy zacząć tutaj.',
    beyond: [
      { nr: '01', n: 'Wdrożenie AI', p: 'od 4 500 zł', d: 'Dla firm, które mają już klientów i chcą usprawnić konkretny proces. Rozpisuję go, ustalam, co warto zautomatyzować, i buduję potrzebny proces, agenta AI, integrację albo panel.' },
      { nr: '02', n: 'Aplikacja lub system', p: 'od 11 000 zł', d: 'Pierwsza działająca wersja produktu, aplikacji, dashboardu albo systemu dla firmy. Coś, czego można realnie używać od pierwszego dnia.' },
      { nr: '03', n: 'Dalszy rozwój po publikacji', p: 'od 5 500 zł miesięcznie', d: 'Stała współpraca przy wybranych projektach: utrzymanie, kolejne wersje i decyzje produktowe.' },
    ],
    fine: 'Dokładny zakres i cena są znane przed startem · maksymalnie trzy aktywne projekty jednocześnie.',
    exclusion: 'Długoterminowe prowadzenie reklam, stałe SEO i gwarantowane wyniki sprzedażowe nie wchodzą w ten zakres.',
  },
  process: {
    label: '( Proces )',
    h1: 'Tak wygląda',
    h2: 'wspólna praca.',
    steps: [
      ['Rozmawiamy o biznesie', 'Co działa dziś, co trzeba zmienić i po co ma powstać nowa strona. Zaczynamy od 15 minut.'],
      ['Ustalam zakres', 'Dostajesz jasną propozycję: co buduję, czego nie ma w zakresie i ile to kosztuje.'],
      ['Rezerwujesz termin', 'Praca jest opłacana przed startem: w całości przy małych projektach, etapami przy większych.'],
      ['Buduję', 'Ta sama osoba, która rozmawiała z tobą o biznesie, pisze, projektuje i wdraża.'],
      ['Publikujemy', 'Strona lub system trafia do ludzi i zaczyna być używany w realnym świecie.'],
      ['Rozwijamy, kiedy ma to sens', 'Stała współpraca przy wybranych projektach. Dalszy rozwój od 5 500 zł miesięcznie.'],
    ],
  },
  faq: {
    label: '( Uczciwe pytania )',
    items: [
      ['Czy AI może zbudować za mnie stronę?', 'AI potrafi wygenerować tekst, układ i kod. Trudniejsze jest zdecydowanie, czy wynik jest jasny, wiarygodny i pasuje do biznesu. Samo użycie AI nie jest problemem. Doświadczenie przydaje się przy decyzji, co zostawić, co usunąć i co zbudować od nowa.'],
      ['Czy muszę przygotować wszystkie treści?', 'Nie. Treść może być częścią projektu. Potrzebuję jednak prawdziwych informacji o biznesie, klientach i ofercie. Nie wymyślam wyników, opinii ani obietnic tylko po to, żeby wypełnić stronę.'],
      ['Czy robisz tylko strony internetowe?', 'Strony firmowe i ofertowe są głównym kierunkiem. Buduję też wdrożenia AI, aplikacje, dashboardy i wewnętrzne systemy, jeśli projekt potrzebuje czegoś więcej niż publiczna strona.'],
      ['Czy jesteś agencją?', 'Nie. Od pierwszej rozmowy do wdrożenia pracujesz bezpośrednio ze mną. Prowadzę maksymalnie trzy aktywne projekty jednocześnie.'],
      ['Co obejmuje 30 dni poprawek po publikacji?', 'Przez 30 dni po publikacji bez dodatkowej opłaty naprawiam wszystko, co mieści się w uzgodnionym zakresie i nie działa zgodnie z ustaleniami. Nowe elementy i zmiany poza zakresem wyceniam osobno. To zabezpieczenie jakości wykonanej pracy, nie gwarancja wyniku biznesowego.'],
      ['Czy gwarantujesz wyniki?', 'Nie. Nie gwarantuję przychodu ani konkretnego wyniku marketingowego. Sama nowa strona nie naprawi też niejasnej oferty. Ustalam problem, buduję uzgodnione rozwiązanie i daję ci coś realnego do pokazania klientom. Reszta zależy również od oferty, ruchu, rynku i tego, jak firma korzysta z gotowej strony.'],
    ],
  },
  footer: {
    label: '( Porozmawiajmy )',
    h1: 'Najpierw ustalmy,',
    h2: 'co naprawdę trzeba zbudować.',
    sub: 'Opowiedz mi, co masz dziś, nawet jeśli nie ma jeszcze nic. Powiem ci wprost, czy ten projekt pasuje do mojego sposobu pracy i co zbudowałbym najpierw.',
    write: 'albo po prostu napisz',
    contact: 'Kontakt',
    badge: 'WROCŁAW, POLSKA · PRACUJĘ ZDALNIE ·',
    availability: 'Dostępność',
    availability1: 'Maksymalnie trzy aktywne projekty jednocześnie',
    availability2: 'Zaczynamy od jednej konkretnej rozmowy',
    top: 'Wróć na początek',
    built: 'Zaprojektowane i zbudowane przez jedną osobę',
    terms: 'Warunki',
    privacy: 'Prywatność',
  },
} as const;
